config/routes.rb
Galeria::Application.routes.draw do
  devise_for :users

  resources :galleries do
    get :pictures
  end
  root :to => 'galleries#index'
  resources :pictures
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :nome, :descricao

  validates_presence_of :nome
  validates_presence_of :descricao
  
  has_many :pictures, dependent: :destroy
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :gallery # representacao da chave estrangeira
  
  attr_accessible :nome, :gallery_id, :image
  
  validates_presence_of :nome
  
  validates_presence_of :gallery_id
  
  mount_uploader :image, ImageUploader  # monta o uploader no campo image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  
  before_filter :find_gallery, except: [:index, :new, :create, :pictures]
  before_filter :authenticate_user!
   
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  def edit
  end

  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end
  
  def pictures
    @gallery = Gallery.find(params[:gallery_id])
    @pictures = Picture.where(gallery_id: @gallery)
    # A query acima pode ser feita da forma abaixo pois fizemos as ligacoes entre modelos
    # @pictures = @gallery.pictures
  end
  
  protected
  
  def find_gallery
    @gallery = Gallery.find(params[:id])
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  
  before_filter :authenticate_user!
  
  before_filter :find_picture, only: [:show, :edit, :update, :destroy]
  
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  def edit
  end

  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end
  
  protected
  
  def find_picture
    @picture = Picture.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(resource)
    render "layouts/error_message", resource: resource
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>

  <%= error_messages_for(@gallery) %>
  
  <p><%= f.label :nome %>
  <%= f.text_field :nome %></p>
  
  <p><%= f.label :descricao %>
  <%= f.text_field :descricao %></p>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<h1>Listing galleries</h1>

<table border=1>
  <tr>
    <th>Nome</th>
    <th>Descrição</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @galleries.each do |gallery| %>
  <tr>
    <td><%= gallery.nome %></td>
    <td><%= gallery.descricao %></td>
    <td><%= link_to 'Show', gallery %></td>
    <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
    <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to "Pictures", gallery_pictures_path(gallery) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/pictures.html.erb
<h1>Gallery: <%= @gallery.nome %></h1>

<div id="pictures">
  <% @pictures.each do |picture| %>
    <div class="picture">
      <%= image_tag picture.image_url, size: "200x200" if picture.image? %>
      <div class="name"><%= picture.nome %></div>
      <div class="actions">
        <%= link_to "edit", edit_picture_path(picture) %> |
        <%= link_to "remove", picture, :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @gallery.nome %></h2>
<p><%= @gallery.descricao %></p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

app/views/layouts/_error_message.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %>:</h2>

    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Galeria</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <ul class="menu">
    <li><%= link_to "Galleries", galleries_path %></li>
    <li><%= link_to "Pictures", pictures_path %></li>
  </ul>
  
  <% if user_signed_in? %>
    <ul class="menu right">
      <li><%= current_user.email %></li>
      <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
    </ul>
  <% end %>
  
  <%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  
  <%= error_messages_for(@picture) %>
  
  <p><%= f.label :nome %>
  <%= f.text_field :nome %></p>
  
  <p><%= f.label :gallery_id %>
  <%= f.select :gallery_id, Gallery.all.collect{ |gallery| [gallery.nome, gallery.id] }, include_blank: true %></p>
  
  <p><%= f.label :image %>
  <%= f.file_field :image %></p>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table border=1>
  <tr>
    <th>Nome</th>
    <th>Gallery</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.nome %></td>
    <td><%= picture.gallery.nome %></td>
    <td><%= link_to 'Show', picture %></td>
    <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
    <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @picture.gallery.nome %></h2>
<p><%= image_tag @picture.image_url, size: "250x250" %></p>
<p><%= @picture.nome %></p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>